dist: trusty #bionic
sudo: true
language: cpp
branches: 
  only:
    - inprogress
addons:
  apt:
    sources:
      - "ubuntu-toolchain-r-test"
    packages:
      - "gcc-6"
      - "g++-6"
      - "cmake-data"
      - "cmake"
      - "lcov"
    git:
      submodules: false 

before_script:
  - "sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules"
  - "git submodule update --init --recursive"
  - "gem install coveralls-lcov" # this ruby package is much easier to work with than the python package cpp-coveralls
  # next 4 lines are for mkl
  - "wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB"
  - "sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB"
  - "sudo sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'"
  - "sudo apt-get -y update"
  - "sudo apt-get install -y intel-mkl-2019.0-045"
script:
  - "./build-cpu 2"

after_script:

after_success:
  - cd ${TRAVIS_BUILD_DIR}/debug-ann-cpu
  - coveralls-lcov --repo-token "$ANN_COVERALLS_REPO_TOKEN" ann_coverage.info

notifications:
  email: true

